spring.application.name=api

# falta configurar, comentado apenas para testar . 

#spring.datasource.url=jdbc:postgresql://localhost:5432/presenca
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.hibernate.ddl-auto=validate
